let min_t = datetime(2022-05-24 09:11);
let max_t = datetime(2022-05-24 15:00);
let dt = 2h;
boltmaker
| make-series num=avg(kwh) on messageTimestamp from min_t to max_t step dt by deviceId 
| extend (anomalies, score, baseline) = series_decompose_anomalies(num, 1.5, -1, 'linefit')
| render anomalychart with(anomalycolumns=anomalies, title='Anomalies kWh usage per machine in production line')
